const songs = [
    {
      serial: 1,
      name: "Blinding Lights",
      artist: "The Weeknd",
      album: "After Hours",
      duration: "3:20",
      image: "https://via.placeholder.com/150?text=Blinding+Lights",
      popularity: 85,
      previewUrl: "https://p.scdn.co/mp3-preview/1",
    },
    {
      serial: 2,
      name: "Shape of You",
      artist: "Ed Sheeran",
      album: "Divide",
      duration: "4:23",
      image: "https://via.placeholder.com/150?text=Shape+of+You",
      popularity: 90,
      previewUrl: "https://p.scdn.co/mp3-preview/2",
    },
    {
      serial: 3,
      name: "Rolling in the Deep",
      artist: "Adele",
      album: "21",
      duration: "3:48",
      image: "https://via.placeholder.com/150?text=Rolling+in+the+Deep",
      popularity: 88,
      previewUrl: "https://p.scdn.co/mp3-preview/3",
    },
    {
      serial: 4,
      name: "Levitating",
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      duration: "3:30",
      image: "https://via.placeholder.com/150?text=Levitating",
      popularity: 82,
      previewUrl: "https://p.scdn.co/mp3-preview/4",
    },
    {
      serial: 5,
      name: "Stay",
      artist: "The Kid LAROI, Justin Bieber",
      album: "Stay",
      duration: "2:21",
      image: "https://via.placeholder.com/150?text=Stay",
      popularity: 95,
      previewUrl: "https://p.scdn.co/mp3-preview/5",
    },
    {
      serial: 6,
      name: "Bad Guy",
      artist: "Billie Eilish",
      album: "When We All Fall Asleep, Where Do We Go?",
      duration: "3:14",
      image: "https://via.placeholder.com/150?text=Bad+Guy",
      popularity: 89,
      previewUrl: "https://p.scdn.co/mp3-preview/6",
    },
    {
      serial: 7,
      name: "Uptown Funk",
      artist: "Mark Ronson ft. Bruno Mars",
      album: "Uptown Special",
      duration: "4:31",
      image: "https://via.placeholder.com/150?text=Uptown+Funk",
      popularity: 93,
      previewUrl: "https://p.scdn.co/mp3-preview/7",
    },
    {
      serial: 8,
      name: "Happier",
      artist: "Marshmello ft. Bastille",
      album: "Happier",
      duration: "3:34",
      image: "https://via.placeholder.com/150?text=Happier",
      popularity: 87,
      previewUrl: "https://p.scdn.co/mp3-preview/8",
    },
    {
      serial: 9,
      name: "Someone Like You",
      artist: "Adele",
      album: "21",
      duration: "4:45",
      image: "https://via.placeholder.com/150?text=Someone+Like+You",
      popularity: 91,
      previewUrl: "https://p.scdn.co/mp3-preview/9",
    },
    {
      serial: 10,
      name: "Despacito",
      artist: "Luis Fonsi ft. Daddy Yankee",
      album: "Vida",
      duration: "3:50",
      image: "https://via.placeholder.com/150?text=Despacito",
      popularity: 98,
      previewUrl: "https://p.scdn.co/mp3-preview/10",
    },
  ];
  
  export default songs;
  